-- ============================================================
-- M9 remediation: idempotency on /payment/initiate
-- ============================================================
-- Adds a UNIQUE constraint on (merchant_id, reference) so that
-- a merchant cannot accidentally or deliberately create two
-- transactions with the same reference. The constraint is
-- partial — only applies when reference IS NOT NULL (auto-
-- generated references are always unique by construction).
--
-- ⚠️ Before applying this migration, run this query on production
-- to check for existing duplicates:
--
--   SELECT merchant_id, reference, count(*) AS dup_count
--   FROM public.transactions
--   WHERE reference IS NOT NULL
--   GROUP BY merchant_id, reference
--   HAVING count(*) > 1
--   ORDER BY dup_count DESC;
--
-- If any rows are returned, the migration will FAIL because the
-- UNIQUE constraint cannot be created with duplicate data. You
-- must resolve the duplicates first (e.g. by appending a suffix
-- to the reference of the non-terminal duplicate, or by
-- cancelling the duplicate transaction).

-- ── 1. UNIQUE constraint on (merchant_id, reference) ─────────
-- Partial index: only enforces uniqueness when reference IS NOT NULL.
-- NULL references are allowed (auto-generated by initiate.ts).
CREATE UNIQUE INDEX IF NOT EXISTS transactions_merchant_reference_unique
  ON public.transactions (merchant_id, reference)
  WHERE reference IS NOT NULL;
