-- ════════════════════════════════════════════════════════════════════════════
-- Formalise the merchants.webhook_url + merchants.webhook_secret columns.
--
-- These columns already exist in production (added manually when the
-- merchant webhook feature was introduced in commit 1beb3b2, but no
-- migration was created at the time). This migration makes the schema
-- reproducible for fresh environments and CI.
--
-- webhook_url:     the merchant's HTTPS endpoint where UniPay POSTs
--                  transaction status updates (event: payment.status_update).
--                  Set by the merchant via POST /v1/merchant/webhook or
--                  by the admin via PUT /v1/admin/merchants/:id/webhook-url.
-- webhook_secret:  HMAC-SHA-256 secret used to sign outgoing webhook
--                  payloads (X-UniPay-Signature header). Auto-generated
--                  when the merchant configures their webhook via the
--                  self-service endpoint. The admin webhook-url endpoint
--                  does NOT regenerate the secret (use the merchant
--                  self-service endpoint for that).
--
-- This migration is idempotent (ADD COLUMN IF NOT EXISTS) and safe to run
-- on production where the columns already exist.
-- ════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.merchants
  ADD COLUMN IF NOT EXISTS webhook_url text;

ALTER TABLE public.merchants
  ADD COLUMN IF NOT EXISTS webhook_secret text;

COMMENT ON COLUMN public.merchants.webhook_url IS
  'Merchant HTTPS webhook endpoint for transaction status callbacks. Optional. Set by merchant (POST /v1/merchant/webhook) or admin (PUT /v1/admin/merchants/:id/webhook-url).';

COMMENT ON COLUMN public.merchants.webhook_secret IS
  'HMAC-SHA-256 secret for signing outgoing webhook payloads (X-UniPay-Signature header). Auto-generated by the merchant self-service webhook endpoint.';
