/**
 * Regression test: API key generated by /merchant/register must authenticate
 * via the hmac plugin verification.
 *
 * This test would have FAILED before the fix:
 *   - register.ts hashed keys with bcrypt (salted $2a$10$... format)
 *   - hmac.ts verified with crypto.createHash('sha256') (hex digest)
 *   - These two formats can never match → every merchant was locked out.
 *
 * After the fix, hmac.ts uses bcrypt.compare, so the round-trip works.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import bcrypt from 'bcryptjs';

function source(relativePath: string): string {
  return fs.readFileSync(path.resolve(process.cwd(), relativePath), 'utf8');
}

describe('API key auth round-trip (register → hmac verification)', () => {
  // Mirror of register.ts key generation logic.
  function generateKeyLikeRegister(): { rawKey: string; keyHash: string; keyPrefix: string } {
    const rawKey = `up_${crypto.randomBytes(16).toString('hex')}`;
    const keyHash = bcrypt.hashSync(rawKey, 10);
    const keyPrefix = rawKey.slice(0, 12);
    return { rawKey, keyHash, keyPrefix };
  }

  // Mirror of hmac.ts verification logic (post-fix).
  async function verifyKeyLikeHmac(
    apiKey: string,
    candidates: { key_hash: string }[],
  ): Promise<boolean> {
    for (const k of candidates) {
      if (await bcrypt.compare(apiKey, k.key_hash)) return true;
    }
    return false;
  }

  it('a key generated by register.ts logic passes hmac.ts verification', async () => {
    const { rawKey, keyHash } = generateKeyLikeRegister();
    const ok = await verifyKeyLikeHmac(rawKey, [{ key_hash: keyHash }]);
    assert.equal(ok, true, 'bcrypt-hashed key must pass bcrypt.compare verification');
  });

  it('rejects a wrong key even when the prefix matches', async () => {
    const { keyHash } = generateKeyLikeRegister();
    const ok = await verifyKeyLikeHmac('up_wrongkey0000000000000000000000', [{ key_hash: keyHash }]);
    assert.equal(ok, false);
  });

  it('verifies against the correct candidate when multiple share the prefix', async () => {
    const a = generateKeyLikeRegister();
    const b = generateKeyLikeRegister();
    const ok = await verifyKeyLikeHmac(b.rawKey, [
      { key_hash: a.keyHash },
      { key_hash: b.keyHash },
    ]);
    assert.equal(ok, true);
  });

  it('hmac.ts uses bcrypt.compare (not SHA-256) — static guard against regression', () => {
    const hmac = source('src/plugins/hmac.ts');
    assert.match(hmac, /bcrypt\.compare\s*\(/, 'hmac.ts must use bcrypt.compare for key verification');
    assert.doesNotMatch(
      hmac,
      /createHash\(['"]sha256['"]\)/,
      'hmac.ts must not use SHA-256 for key verification (would never match bcrypt hashes)',
    );
  });

  it('register.ts hashes keys with bcrypt and uses a 12-char prefix', () => {
    const register = source('src/routes/merchant/register.ts');
    assert.match(register, /bcrypt\.hash\(/, 'register.ts must hash keys with bcrypt');
    assert.match(register, /rawKey\.slice\(0,\s*12\)/, 'register.ts must use a 12-char prefix');
  });

  it('apikey.ts uses merchant_id (not operator_id) for api_keys table', () => {
    const apikey = source('src/routes/merchant/apikey.ts');
    assert.match(apikey, /\.eq\('merchant_id'/, 'apikey.ts deactivate must use merchant_id');
    assert.match(apikey, /merchant_id:\s*payload\.merchant_id/, 'apikey.ts insert must use merchant_id');
    assert.doesNotMatch(
      apikey,
      /operator_id/,
      'apikey.ts must not reference operator_id (column does not exist on api_keys)',
    );
  });
});
